### PR TITLE
Simpler install instruction

### PR DESCRIPTION
**Pull request by Anahkiasen**
No need to manually edit the file, Composer will automatically get the correct version constraint and update the composer.json file

### CODE REVIEW

**Comment by vinkla** [comment]
+1 on this!  `dev-master` shouldn't be used within production.

**Comment by vinkla** [comment]
Though, there currently is no released versions. We should add a branch alias in the mean time.

```json
"extra": {
    "branch-alias": {
        "dev-master": "1.0-dev"
    }
},
```

This will allow developers to use this by specifying `1.0.*@dev` instead of `dev-master`.

**Comment by slampenny** [comment]
@vinkla , you can already do this. I do it in my builds, except I use the @ symbol like so: "jlapp/smart-seeder": "5.0.*@dev",

**Comment by vinkla** [comment]
Thats no good either.

**Pull request closed without merging**
